#!/bin/bash

CUR_PWD=$(pwd)
PUPPET_DIR="$(dirname $0)"
ROLE_FILE="/etc/facter/facts.d/role.txt"
PUPPET_MANIFESTS="manifests/site.pp"
PUPPET_MODULES="modules"
PUPPET_HIERA="hiera-data"

RED_TEXT="\e[31m"
GREEN_TEXT="\e[92m"
RESET_TEXT="\e[0m"

# Check if user is root
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Check that this is ubuntu
DIST=$(lsb_release -i | awk '{print $3}')
if [ "$DIST" != "Ubuntu" ]; then
    echo -n -e "$RED_TEXT"
    echo "Unsupported dist. Exiting"
    echo -n -e "$RESET_TEXT"
fi

# Setup trap the cd back to current dir when exit
trap "cd $CUR_PWD" SIGHUP SIGINT SIGTERM EXIT

cd $PUPPET_DIR

# Check if puppet-common is installed
dpkg-query -l puppet-common > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo -e "$RED_TEXT"
    echo "Puppet-common is not installed. Installing it now..."
    echo -e "$RESET_TEXT"
    apt-get install -y puppet-common
fi

# Check if git is installed
dpkg-query -l git > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo -e "$RED_TEXT"
    echo "Git is not installed. Installing it now..."
    echo -e "$RESET_TEXT"
    apt-get install -y git
fi

# Check if we have the deep_merge gem installed. (required by hiera)
gem spec deep_merge > /dev/null 2>&1
if [ "$?" != "0" ]; then
    echo -e "$RED_TEXT"
    echo "Deep_merge is not installed. Installing it now..."
    echo -e "$RESET_TEXT"
    gem install deep_merge
fi



# Ask user if it's a server or desktop installation
if [ ! -f $ROLE_FILE ]; then
    # Check if facter dir exists. If not creates it.
    if [ ! -d $(dirname $ROLE_FILE) ]; then
	mkdir -p $(dirname $ROLE_FILE)
    fi
    while true; do
	clear
	echo "Is this server or desktop installation?"
	echo "Type [d]esktop or [s]erver to choose"
	read -s -n 1 CHOICE
	case $CHOICE in
	    d)
		echo "role=Desktop" > $ROLE_FILE
		break
		;;
	    s)
		echo "role=Server" > $ROLE_FILE
		break
		;;
	    *)
		clear
		echo "You typed $CHOICE, it needs to be [d]esktop or [s]erver"
		;;
	esac
    done
    clear
    echo -e -n "$GREEN_TEXT"
    echo "You choosed your system to be a $(facter role). Will now run puppet... :)"
    echo -e -n "$RESET_TEXT"
fi


# Sets up temp hiera config file
HIERA_CONFIG=$(tempfile -p hiera -s .yaml)
trap "rm $HIERA_CONFIG" SIGHUP SIGINT SIGTERM EXIT
cat "$PUPPET_HIERA/hiera.yaml" | sed "s|<%HIERA_DATADIR_DONT_CHANGE%>|$PUPPET_HIERA|" > $HIERA_CONFIG


# Runs puppet
#git pull
puppet apply --modulepath "$PUPPET_MODULES" --hiera_config="$HIERA_CONFIG" "$PUPPET_MANIFESTS" --parser future $@
