---
language: ruby
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.4
script: bundle exec rake spec
env:
  matrix:
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.8.0"
  - PUPPET_VERSION="~> 4.3"
